# -*- coding: utf-8 -*-
"""Alice_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqB6nMhVqzN5J0sJMMJRPXJb1JvV-cZi

1. 数据集准备
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras import optimizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input
import os

# Check if the text file exists
if not os.path.exists('alice_in_wonderland.txt'):
    print("Error: alice_in_wonderland.txt not found!")
    print("Please make sure the file exists in the current directory.")
    exit(1)

# 打开并读取文本文件
with open('alice_in_wonderland.txt', 'r', encoding='utf-8') as file:
    text = file.read()

print('Text length:', len(text))

# 初始化两个列表
segments = []  # 用于存储长度为60的字符片段
next_chars = []  # 用于存储对应的下一个字符

# 设置步长和片段长度
step = 3
sequence_length = 60

# 遍历文本，提取片段和对应的下一个字符
for i in range(0, len(text) - sequence_length, step):
    # 提取长度为60的字符片段
    segment = text[i:i + sequence_length]
    # 提取对应的下一个字符
    next_char = text[i + sequence_length]
    # 将片段和下一个字符分别添加到对应的列表中
    segments.append(segment)
    next_chars.append(next_char)

# 打印部分结果，用于验证
print(f"Number of sequences: {len(segments)}")
print(f"Example segment: {segments[50]}")
print(f"Example next char: {next_chars[50]}")

"""2. Character to Vector

不需要Word Embedding，这是因为之前用的是word level tokenization，常用英文单词有10000个，one-hot向量维度太高了，所以要用word embedding降维为低维词向量；但做文本生成是character level tokenization，使用的字符只有几十一百个，维度不高。
"""

# 构建字符字典
chars = sorted(list(set(text)))  # 获取所有唯一字符
char_to_index = {char: index for index, char in enumerate(chars)}  # 字符到索引的映射
index_to_char = {index: char for index, char in enumerate(chars)}  # 索引到字符的映射

num_chars = len(char_to_index)
print(f"Number of unique characters: {num_chars}")

num_sequences = len(segments)
# 初始化输入矩阵和目标向量
X = np.zeros((num_sequences, sequence_length, num_chars), dtype=bool)  # 输入矩阵
y = np.zeros((num_sequences, num_chars), dtype=bool)  # 目标向量

# 填充输入矩阵和目标向量
for i, segment in enumerate(segments):
    for t, char in enumerate(segment):
        X[i, t, char_to_index[char]] = 1  # One-Hot 编码
    y[i, char_to_index[next_chars[i]]] = 1  # One-Hot 编码

# 打印部分结果，用于验证
print(f"Example input sequence shape: {X[50].shape}")
print(f"Example target character shape: {y[50].shape}")

"""3. build a NN"""

model = Sequential([
    Input(shape=(sequence_length, num_chars)),  # 输入60x71 片段长度60，one-hot向量 71维
    LSTM(128),  # 状态向量的维度：128
    Dense(num_chars, activation="softmax")  # 全连接层输出71维，使用softmax激活函数生成概率分布
])
model.summary()

optimizer = optimizers.RMSprop(learning_rate=0.01)
model.compile(loss='categorical_crossentropy', optimizer=optimizer)

"""4. 训练神经网络"""

history = model.fit(X, y, batch_size=128, epochs=5)
model.save("alice_generator.keras")

"""预测下一个字符"""

def sample_with_temperature(preds, temperature=1.0):
    """
    根据温度参数从预测的概率分布中选择字符
    :param preds: 模型预测的概率分布
    :param temperature: 温度参数，控制生成的多样性
    :return: 选择的字符索引
    """
    preds = np.asarray(preds).astype('float64')
    # 公式1：调整概率分布的锐度
    preds = preds ** (1 / temperature)
    # 公式2：归一化概率分布
    preds = preds / np.sum(preds)

    # 从调整后的概率分布中随机选择字符
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)

# 定义文本生成函数
def generate_text(model, seed_text, length=400, temperature=0.5):
    generated = ''
    generated += seed_text
    sentence = seed_text

    for i in range(length):
        x_pred = np.zeros((1, sequence_length, num_chars))
        for t, char in enumerate(sentence):
            x_pred[0, t, char_to_index[char]] = 1

        preds = model.predict(x_pred, verbose=0)[0]
        next_index = sample_with_temperature(preds, temperature)
        next_char = index_to_char[next_index]

        generated += next_char
        sentence = sentence[1:] + next_char

    return generated

# 准备种子文本
seed_text = "Alice was captured by Queen when the rabbit says: `why do cr"
print(f"Seed text length: {len(seed_text)}")

# 测试生成下一个字符
X_in = np.zeros((1, 60, num_chars), dtype=bool)  # 输入矩阵
for t, char in enumerate(seed_text):
    X_in[0, t, char_to_index[char]] = 1

preds = model.predict(X_in, verbose=0)[0]  # verbose=0表示不输出日志信息，[0]是因为输出的第一维是batch size
print(f"Prediction shape: {preds.shape}")

next_index = sample_with_temperature(preds, temperature=0.5)
next_char = index_to_char[next_index]
print(f"Next character: {next_char}")

# 生成文本1
print("Generated Text (temperature=0.5):")
generated_text = generate_text(model, seed_text, length=400, temperature=0.5)
print(generated_text)

# 生成文本1
print("\nGenerated Text (temperature=0.3):")
generated_text = generate_text(model, seed_text, length=400, temperature=0.3)
print(generated_text)

seed_text2 = "Alice was beginning to get very tired of sitting by her sist"

# 生成文本2
print("\nGenerated Text 2 (temperature=0.3):")
generated_text = generate_text(model, seed_text2, length=400, temperature=0.3)
print(generated_text)

# 生成文本2
print("\nGenerated Text 2 (temperature=0.5):")
generated_text = generate_text(model, seed_text2, length=400, temperature=0.5)
print(generated_text)